# Site settings
title: Yoon Kean
description: This is Siaw Yoon Kean Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Siaw Yoon Kean
user_description: TBH.
user_title: Software Developer
email: yonkean@gmail.com
github_username:  yoonkean

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
